layout_spectrum: 0.6637089585419744
typography_spectrum: 0.6665211927611381
color:
  brandStrength: 0.5231358979362994
  lightness: 0.2591778445057571
  saturation: 0.9886219017207623
  rhythmicContrast: 0.8347837859764695
  brandColors:
    - '#7D8A2E'
    - '#C9D787'
    - '#FFFFFF'
    - '#FFC0A9'
    - '#FF8598'
name: Walltip
navigation:
  - name: Test
    id: bd437bec-9e4c-40a7-9276-c3f956a7d10d
    type: content
  - name: My Life
    url: martynaskairys.com
    type: external
  - name: Life
    url: 'http://martynaskairys.com'
    type: external
  - name: mike
    id: ce29dbfd-21d0-4d81-8524-21af5cfcfc71
    type: content
